In [3]:
import pandas as pd

In [3]:
df=pd.read_csv(r'C:\Users\Good Day\Desktop\projects\Crimes_-_2001_to_Present.csv')
df.head(2)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,08/25/2007 09:22:18 AM,074XX N ROGERS AVE,0560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,08/17/2015 03:03:40 PM,NaN,NaN,NaN
1,25953,JE240540,05/24/2021 03:06:00 PM,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)"

In [4]:
df.shape

(8077151, 22)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8077151 entries, 0 to 8077150
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.2+ GB

In [6]:
df.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description     13087
Arrest                       0
Domestic                     0
Beat                         0
District                    47
Ward                    614846
Community Area          613470
FBI Code                     0
X Coordinate             88958
Y Coordinate             88958
Year                         0
Updated On                   0
Latitude                 88958
Longitude                88958
Location                 88958
dtype: int64

In [7]:
# Remove Latitude and Longitude Null values - Since Null value <1%

df1=df.dropna(subset=['Location Description','District','Latitude', 'Longitude'])

In [8]:
df1.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description         0
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    605586
Community Area          604264
FBI Code                     0
X Coordinate                 0
Y Coordinate                 0
Year                         0
Updated On                   0
Latitude                     0
Longitude                    0
Location                     0
dtype: int64

In [9]:
df1['Location Description'].nunique()

217

In [10]:
df1['Ward'].nunique()

50

In [11]:
df1['Community Area'].nunique()

78

In [12]:
df2=df1.groupby('Location Description')[['Ward', 'Community Area']].agg(lambda x:x.unique().tolist())
df2

,Ward,Community Area
Location Description,,
ABANDONED BUILDING,"[28.0, 22.0, 40.0, 7.0, 27.0, 26.0, 20.0, 16.0...","[25.0, 29.0, 2.0, 43.0, 28.0, 24.0, 42.0, 67.0..."
AIRCRAFT,"[13.0, 41.0, 50.0, 14.0, 36.0, 23.0, 33.0, 28....","[56.0, 76.0, 13.0, 66.0, 19.0, 16.0, 25.0, 67...."
AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,"[41.0, 13.0, 30.0, 23.0, 4.0, 49.0, nan, 31.0,...","[76.0, 56.0, 19.0, 32.0, 1.0, 64.0, 22.0, 6.0,..."
AIRPORT BUILDING NON-TERMINAL - SECURE AREA,"[41.0, 13.0, 48.0, nan, 23.0, 4.0, 20.0, 47.0,...","[76.0, 56.0, 77.0, 36.0, 64.0, 68.0, 3.0, 69.0..."
AIRPORT EXTERIOR - NON-SECURE AREA,"[41.0, 13.0, 23.0, 46.0, 42.0, nan, 5.0, 3.0, ...","[76.0, 56.0, 64.0, 6.0, 8.0, 5.0, 57.0, 62.0, ..."
...,...,...
VESTIBULE,"[4.0, 8.0, 38.0, 5.0, 17.0, 22.0, 28.0, 3.0, 7...","[35.0, 44.0, 15.0, 39.0, 66.0, 30.0, 27.0, 40...."
WAREHOUSE,"[17.0, 27.0, 37.0, 22.0, 10.0, 14.0, 18.0, 24....","[67.0, 8.0, 23.0, 25.0, 30.0, 52.0, 55.0, 63.0..."
WOODED AREA,"[10.0, 9.0, nan, 5.0]","[51.0, 54.0, nan, 42.0]"
YARD,"[8.0, 17.0, 37.0, 5.0, 4.0, 6.0, 38.0, 21.0, 1...","[44.0, 71.0, 25.0, 48.0, 42.0, 39.0, 69.0, 17...."
YMCA,"[44.0, 3.0, 26.0]","[6.0, 38.0, 22.0]"

In [13]:
df3=df1.groupby('Location Description')[['Location']].agg(lambda x: x.unique().tolist())
df3

                                                                                          Location
Location Description
ABANDONED BUILDING                               [(41.880510667, -87.744040233), (41.851467867,...
AIRCRAFT                                         [(41.785038992, -87.751885635), (41.787526687,...
AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA  [(41.976290414, -87.905227221), (41.994913946,...
AIRPORT BUILDING NON-TERMINAL - SECURE AREA      [(41.976290414, -87.905227221), (41.976182125,...
AIRPORT EXTERIOR - NON-SECURE AREA               [(41.98094397, -87.878656365), (41.976182125, ...
...                                                                                            ...
VESTIBULE                                        [(41.829651528, -87.614451899), (41.748737209,...
WAREHOUSE                                        [(41.75898158, -87.663632474), (41.901496787, ...
WOODED AREA                                      [(41.680522215, -87.559329161), (41.658601587,...
YARD                                             [(41.74766347, -87.601874532), (41.745901647, ...
YMCA                                             [(41.942257928, -87.669951491), (41.803391597,...

[217 rows x 1 columns]

In [14]:
df4=df1.groupby('District')[['Ward', 'Community Area']].agg(lambda x:x.unique().tolist())
df4

,Ward,Community Area
District,,
1.0,"[42.0, 4.0, 3.0, 28.0, 34.0, 25.0, 11.0, 2.0, ...","[32.0, 35.0, 33.0, 28.0, 34.0, nan, 0.0, 76.0,..."
2.0,"[3.0, 20.0, 4.0, 5.0, 11.0, nan, 2.0, 25.0, 16...","[38.0, 40.0, 39.0, 35.0, 37.0, 36.0, 41.0, 68...."
3.0,"[7.0, 5.0, 20.0, 8.0, 6.0, nan, 3.0, 4.0, 16.0...","[43.0, 69.0, 42.0, 40.0, 68.0, 41.0, nan, 35.0..."
4.0,"[10.0, 8.0, 7.0, 5.0, 16.0, nan, 19.0, 17.0, 2...","[52.0, 45.0, 46.0, 48.0, 51.0, 43.0, 55.0, 47...."
5.0,"[9.0, 10.0, 8.0, 21.0, 34.0, nan, 6.0, 5.0, 3....","[50.0, 54.0, 49.0, 53.0, 51.0, nan, 72.0, 43.0..."
6.0,"[6.0, 8.0, 17.0, 18.0, 9.0, 21.0, nan, 5.0, 29...","[44.0, 71.0, 49.0, 69.0, 68.0, 67.0, 47.0, 70...."
7.0,"[6.0, 17.0, 16.0, 20.0, 15.0, nan, 3.0, 12.0, ...","[69.0, 67.0, 68.0, nan, 58.0, 43.0, 66.0, 71.0..."
8.0,"[14.0, 18.0, 23.0, 17.0, 22.0, 16.0, 15.0, 12....","[63.0, 70.0, 65.0, 66.0, 56.0, 58.0, 57.0, 62...."
9.0,"[11.0, 15.0, 20.0, 16.0, 12.0, 14.0, 3.0, 25.0...","[60.0, 61.0, 33.0, 34.0, 58.0, 63.0, 37.0, 59...."
10.0,"[24.0, 22.0, 25.0, 28.0, 12.0, nan, 14.0, 11.0...","[29.0, 30.0, 31.0, 28.0, 56.0, nan, 70.0, 33.0..."
11.0,"[28.0, 37.0, 24.0, 27.0, 26.0, 36.0, 29.0, nan...","[27.0, 26.0, 23.0, 25.0, 29.0, 28.0, nan, 24.0..."
12.0,"[27.0, 26.0, 36.0, 28.0, 25.0, 34.0, 1.0, 11.0...","[28.0, 24.0, 23.0, 31.0, 27.0, 43.0, nan, 60.0..."
14.0,"[1.0, 35.0, 26.0, 32.0, 27.0, 2.0, 33.0, nan, ...","[24.0, 22.0, 21.0, 23.0, nan, 29.0, 30.0, 7.0,..."
15.0,"[29.0, 37.0, 28.0, 24.0, nan, 23.0, 15.0, 42.0...","[25.0, nan, 56.0, 67.0, 8.0, 68.0, 27.0]"
16.0,"[39.0, 45.0, 31.0, 38.0, 41.0, 30.0, 36.0, 29....","[11.0, 15.0, 10.0, 9.0, 76.0, 17.0, 12.0, nan,..."
17.0,"[50.0, 30.0, 39.0, 33.0, 45.0, 35.0, 40.0, nan...","[13.0, 21.0, 14.0, 15.0, 16.0, 12.0, nan, 2.0,..."
18.0,"[27.0, 42.0, 32.0, 43.0, 2.0, nan, 47.0, 30.0,...","[8.0, 7.0, nan, 32.0, 28.0, 24.0, 4.0, 19.0, 2..."
19.0,"[47.0, 46.0, 32.0, 40.0, 44.0, 43.0, 7.0, nan,...","[5.0, 6.0, 3.0, 4.0, 7.0, 43.0, nan, 77.0, 22...."
20.0,"[48.0, 40.0, 50.0, 47.0, 46.0, 39.0, nan, 33.0...","[3.0, 77.0, 4.0, 2.0, nan, 14.0, 11.0, 32.0, 1..."
21.0,[3.0],[35.0]
22.0,"[21.0, 18.0, 19.0, 9.0, 34.0, 16.0, nan, 10.0,...","[73.0, 75.0, 71.0, 74.0, 72.0, 49.0, 67.0, nan..."
24.0,"[49.0, 50.0, 48.0, 40.0, nan, 2.0, 41.0, 15.0,...","[1.0, 2.0, 77.0, nan, 13.0, 32.0, 10.0, 66.0, ..."
25.0,"[36.0, 29.0, 30.0, 26.0, 31.0, 37.0, 35.0, 27....","[19.0, 25.0, 22.0, 23.0, 20.0, 21.0, 18.0, 17...."
31.0,"[41.0, 37.0, nan, 50.0, 42.0, 36.0, 19.0, 9.0,...","[76.0, 23.0, nan, 2.0, 0.0, 32.0, 10.0, 17.0, ..."

In [15]:
# since there is no unique ward and community area wrt to Location and district - missing value to be filled with mode.

df1['Ward']=df1['Ward'].fillna(df['Ward'].mode()[0])
df1['Community Area']=df1['Community Area'].fillna(df['Community Area'].mode()[0])

C:\Users\Good Day\AppData\Local\Temp\ipykernel_4360\2458712135.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Ward']=df1['Ward'].fillna(df['Ward'].mode()[0])
C:\Users\Good Day\AppData\Local\Temp\ipykernel_4360\2458712135.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Community Area']=df1['Community Area'].fillna(df['Community Area'].mode()[0])

In [16]:
df1.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [17]:
df=df1.copy()

In [18]:
df.head(2)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
1,25953,JE240540,05/24/2021 03:06:00 PM,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,06/26/2021 09:24:00 AM,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,11/18/2023 03:39:49 PM,41.995219,-87.713355,"(41.995219444, -87.713354912)"

In [19]:
df.shape

(7979798, 22)

In [20]:
print(df['Date'])

1          05/24/2021 03:06:00 PM
2          06/26/2021 09:24:00 AM
3          11/09/2023 07:30:00 AM
4          11/12/2023 07:59:00 AM
6          09/06/2023 05:00:00 PM
                    ...
8077146    04/18/2023 08:00:00 AM
8077147    08/07/2023 06:00:00 PM
8077148    06/20/2023 07:00:00 PM
8077149    08/26/2023 12:00:00 AM
8077150    07/01/2023 07:29:00 PM
Name: Date, Length: 7979798, dtype: object

In [21]:
# Split Date and Time
def split_date_time(df, col):

    try:

        df[col]=pd.to_datetime(df[col], format= '%m/%d/%Y %I:%M:%S %p')
        # Extract Date and Time in DataFrame
        date=df[col].dt.date
        time=df[col].dt.time

        # Create new column for Date and Time

        df['Date']=date
        df['Time']=time

        return df
    except Exception as e:
        print(f'The error Occured:{e}')

df=split_date_time(df, 'Date')

In [22]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Time
1,25953,JE240540,2021-05-24,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)",15:06:00
2,26038,JE279849,2021-06-26,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,13.0,01A,1152781.0,1941458.0,2021,11/18/2023 03:39:49 PM,41.995219,-87.713355,"(41.995219444, -87.713354912)",09:24:00
3,13279676,JG507211,2023-11-09,019XX W BYRON ST,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,5.0,05,1162518.0,1925906.0,2023,11/18/2023 03:39:49 PM,41.952345,-87.677975,"(41.952345086, -87.677975059)",07:30:00
4,13274752,JG501049,2023-11-12,086XX S COTTAGE GROVE AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,44.0,08B,1183071.0,1847869.0,2023,12/09/2023 03:41:24 PM,41.737751,-87.604856,"(41.737750767, -87.604855911)",07:59:00
6,13203321,JG415333,2023-09-06,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)",17:00:00

In [23]:
df.shape

(7979798, 23)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7979798 entries, 1 to 8077150
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
 22  Time                  object
dtypes: bool(2), float64(7), int64(3), object(11)
memory usage: 1.3+ GB

In [25]:
# Change the 'Date' column is of string type
df['Date'] = df['Date'].astype(str)

In [26]:
# Split the 'Date' column
split_dates=df['Date'].str.split("-",expand=True)

# Assign the split components to new columns
df['Year']=split_dates[0]
df['Month']=split_dates[1]
df['Day']=split_dates[2]

In [27]:
df.head(2)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Time,Month,Day
1,25953,JE240540,2021-05-24,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,1141387.0,1913179.0,2021,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)",15:06:00,05,24
2,26038,JE279849,2021-06-26,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,1152781.0,1941458.0,2021,11/18/2023 03:39:49 PM,41.995219,-87.713355,"(41.995219444, -87.713354912)",09:24:00,06,26

In [27]:
# df.to_csv('Crime_data.csv', index=False)

In [28]:
# df=pd.read_csv(r"C:\Users\Good Day\Desktop\projects\Crime_data.csv")

:

In [28]:
df['Case Number'].duplicated().sum()

565

In [29]:
df.shape

(7979798, 25)

In [30]:
df.drop_duplicates(subset='Case Number', inplace=True)

MemoryError: Unable to allocate 487. MiB for an array with shape (8, 7979233) and data type object

In [31]:
df.shape

(7979798, 25)

In [32]:
# Change column Time datatype to str
df['Time']=df['Time'].astype(str)

In [33]:
# Split Time into Hour, minutes and seconds
split_time=df['Time'].str.split(":", expand=True)

# create new columns
df['Hour']=split_time[0]
df['Minute']=split_time[1]
df['Second']=split_time[2]

In [ ]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Updated On,Latitude,Longitude,Location,Time,Month,Day,Hour,Minute,Second
0,25953,JE240540,2021-05-24,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)",15:06:00,5,24,15,06,00
1,26038,JE279849,2021-06-26,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,11/18/2023 03:39:49 PM,41.995219,-87.713355,"(41.995219444, -87.713354912)",09:24:00,6,26,09,24,00
2,13279676,JG507211,2023-11-09,019XX W BYRON ST,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,11/18/2023 03:39:49 PM,41.952345,-87.677975,"(41.952345086, -87.677975059)",07:30:00,11,9,07,30,00
3,13274752,JG501049,2023-11-12,086XX S COTTAGE GROVE AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,12/09/2023 03:41:24 PM,41.737751,-87.604856,"(41.737750767, -87.604855911)",07:59:00,11,12,07,59,00
4,13203321,JG415333,2023-09-06,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)",17:00:00,9,6,17,00,00

In [ ]:
# df.to_csv('Crimes_data.csv', index=False)

In [ ]:
df['Primary Type'].unique()

array(['HOMICIDE', 'BURGLARY', 'BATTERY', 'CRIMINAL DAMAGE',
       'DECEPTIVE PRACTICE', 'CRIMINAL SEXUAL ASSAULT', 'THEFT',
       'OFFENSE INVOLVING CHILDREN', 'ROBBERY', 'ASSAULT',
       'OTHER OFFENSE', 'WEAPONS VIOLATION', 'STALKING',
       'CRIMINAL TRESPASS', 'PROSTITUTION', 'ARSON', 'NARCOTICS',
       'KIDNAPPING', 'CONCEALED CARRY LICENSE VIOLATION',
       'INTERFERENCE WITH PUBLIC OFFICER', 'PUBLIC PEACE VIOLATION',
       'OBSCENITY', 'LIQUOR LAW VIOLATION', 'INTIMIDATION', 'GAMBLING',
       'HUMAN TRAFFICKING', 'OTHER NARCOTIC VIOLATION', 'NON-CRIMINAL',
       'PUBLIC INDECENCY', 'RITUALISM', 'DOMESTIC VIOLENCE'], dtype=object)

In [ ]:
df['Primary Type'].nunique()

31

In [ ]:
df['Description'].unique()

array(['FIRST DEGREE MURDER', 'UNLAWFUL ENTRY',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'TO VEHICLE', 'FINANCIAL IDENTITY THEFT OVER $ 300',
       'NON-AGGRAVATED', '$500 AND UNDER', 'TO PROPERTY', 'OVER $500',
       'FORGERY', 'FROM BUILDING', 'BOGUS CHECK', 'CHILD ABDUCTION',
       'AUTOMOBILE', 'ATTEMPT - FINANCIAL IDENTITY THEFT',
       'ARMED - HANDGUN', 'SIMPLE', 'PREDATORY', 'VEHICULAR HIJACKING',
       'INDECENT SOLICITATION OF A CHILD',
       'HARASSMENT BY ELECTRONIC MEANS',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'SEXUAL EXPLOITATION OF A CHILD',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE', 'RECKLESS FIREARM DISCHARGE',
       'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'CYBERSTALKING', 'AGGRAVATED - OTHER', 'RETAIL THEFT',
       'TO STATE SUP LAND', 'THEFT OF LOST / MISLAID PROPERTY', 'TO LAND',
       'DOMESTIC BATTERY SIMPLE', 'ATTEMPT - AUTOMOBILE',
       'AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',
       'OTHER VEHICLE OFFENSE', 'FALSE / STOLEN / ALTERED TRP',
       'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'VEHICLE TITLE / REGISTRATION OFFENSE', 'AGGRAVATED - HANDGUN',
       'STRONG ARM - NO WEAPON', 'SOLICITING FOR BUSINESS',
       'ILLEGAL USE CASH CARD', 'BY FIRE', 'TO STATE SUPPORTED PROPERTY',
       'TELEPHONE THREAT', 'ATTEMPT FORCIBLE ENTRY', 'FORCIBLE ENTRY',
       'VIOLATE ORDER OF PROTECTION', 'POSSESS - CRACK', 'TO RESIDENCE',
       'THEFT / RECOVERY - AUTOMOBILE',
       'AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY',
       'ENDANGERING LIFE / HEALTH OF CHILD', 'UNLAWFUL RESTRAINT',
       'AGGRAVATED', 'ARMED - OTHER FIREARM',
       'ARMED - OTHER DANGEROUS WEAPON', 'FRAUD OR CONFIDENCE GAME',
       'AGGRAVATED - OTHER DANGEROUS WEAPON', 'CRIMINAL SEXUAL ABUSE',
       'PROHIBITED PLACES', 'OTHER OFFENSE',
       'UNLAWFUL POSSESSION - HANDGUN', 'COUNTERFEITING DOCUMENT',
       'TO CITY OF CHICAGO PROPERTY', 'THEFT OF LABOR / SERVICES',
       'POSSESS - HEROIN (WHITE)', 'CREDIT CARD FRAUD',
       'RESIST / OBSTRUCT / DISARM OFFICER',
       'AGGRAVATED VEHICULAR HIJACKING',
       'NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',
       'THEFT BY LESSEE, MOTOR VEHICLE', 'BOMB THREAT',
       'FINANCIAL EXPLOITATION OF AN ELDERLY OR DISABLED PERSON',
       'AGGRAVATED - HANDS, FISTS, FEET, SERIOUS INJURY',
       'OTHER VIOLATION', 'CYCLE, SCOOTER, BIKE WITH VIN', 'CHILD ABUSE',
       'POSSESS - HEROIN (BLACK TAR)', 'ATTEMPT ARMED - HANDGUN',
       'PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'POCKET-PICKING', 'UNLAWFUL USE - OTHER FIREARM',
       'AGG. PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY',
       'POSSESS - BARBITURATES', 'OTHER CRIME AGAINST PERSON',
       'ATTEMPT AGGRAVATED', 'HOME INVASION',
       'ILLEGAL POSSESSION CASH CARD', 'LICENSE VIOLATION',
       'STOLEN PROPERTY BUY / RECEIVE / POSSESS',
       'HARASSMENT BY TELEPHONE', 'POSSESS - CANNABIS MORE THAN 30 GRAMS',
       'FINANCIAL IDENTITY THEFT $300 AND UNDER',
       'ATTEMPT - CYCLE, SCOOTER, BIKE WITH VIN',
       'SOLICIT NARCOTICS ON PUBLIC WAY', 'COMPUTER FRAUD',
       'POSSESS - COCAINE', 'POSSESS - SYNTHETIC DRUGS',
       'VIOLATION OF STALKING NO CONTACT ORDER',
       'AGGRAVATED FINANCIAL IDENTITY THEFT',
       'UNLAWFUL USE - OTHER DANGEROUS WEAPON',
       'MANUFACTURE / DELIVER - CANNABIS OVER 10 GRAMS',
       'AGGRAVATED OF A SENIOR CITIZEN', 'CHILD PORNOGRAPHY',
       'ATTEMPT THEFT', 'COUNTERFEIT CHECK', 'OTHER', 'PUBLIC INDECENCY',
       'AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',
       'GUN OFFENDER - ANNUAL REGISTRATION', 'FALSE POLICE REPORT',
       'FOUND SUSPECT NARCOTICS',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER DANGEROUS WEAPON',
       'AGGRAVATED DOMESTIC BATTERY - HANDGUN',
       'AGGRAVATED - OTHER FIREARM', 'OBSTRUCTING SERVICE',
       'GUN OFFENDER - DUTY TO REGISTER',
       'AGGRAVATED - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'ATTEMPT ARSON', 'CRIMINAL DEFACEMENT',
       'POSSESSION OF BURGLARY TOOLS',
       'ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT', 'RECKLESS CONDUCT',
       'PURSE-SNATCHING', 'VIOLATION GPS MONITORING DEVICE',
       'AGGRAVATED OF A CHILD', 'POSSESS - CANNABIS 30 GRAMS OR LESS',
       'ANIMAL ABUSE / NEGLECT', 'OBSCENE TELEPHONE CALLS',
       'ATTEMPT STRONG ARM - NO WEAPON',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN',
       'AGGRAVATED POLICE OFFICER - HANDGUN',
       'OTHER CRIME INVOLVING PROPERTY', 'KIDNAPPING',
       'OBSTRUCTING JUSTICE',
       'SALE / DISTRIBUTE OBSCENE MATERIAL TO MINOR', 'EMPLOY MINOR',
       'ARMED - KNIFE / CUTTING INSTRUMENT',
       'POSSESSION OF DRUG EQUIPMENT',
       'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, NO INJURY',
       'SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER', 'OF AN UNBORN CHILD',
       'SELL / GIVE / DELIVER LIQUOR TO MINOR', 'INTIMIDATION',
       'POSSESS - HALLUCINOGENS', 'POSSESS - PCP',
       'CHILD ABDUCTION / STRANGER', 'DECEPTIVE COLLECTION PRACTICES',
       'UNLAWFUL POSSESSION - AMMUNITION', 'UNLAWFUL USE - HANDGUN',
       'AGGRAVATED POLICE OFFICER - KNIFE / CUTTING INSTRUMENT',
       'AGGRAVATED COMPUTER TAMPERING',
       'CONTRIBUTE TO THE DELINQUENCY OF CHILD', 'TRUCK, BUS, MOTOR HOME',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, SERIOUS INJURY',
       'SEX OFFENDER - FAIL TO REGISTER',
       'VIOLATION OF CIVIL NO CONTACT ORDER', 'GAME/DICE',
       'OBSTRUCTING IDENTIFICATION', 'ATTEMPT NON-AGGRAVATED',
       'AGGRAVATED PROTECTED EMPLOYEE - KNIFE / CUTTING INSTRUMENT',
       'UNAUTHORIZED VIDEOTAPING',
       'MANUFACTURE / DELIVER -  HEROIN (WHITE)',
       'LIQUOR LICENSE VIOLATION', 'EMBEZZLEMENT',
       'SOLICIT ON PUBLIC WAY',
       'AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WEAPON',
       'CYCLE, SCOOTER, BIKE NO VIN',
       'VIOLENT OFFENDER - DUTY TO REGISTER',
       'UNLAWFUL USE OF A COMPUTER', 'CHILD ABANDONMENT',
       'POSSESS - METHAMPHETAMINE', 'ESCAPE', 'ARMED VIOLENCE',
       'OBSCENE MATTER', 'SEX OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'ATTEMPT ARMED - OTHER DANGEROUS WEAPON', 'EXTORTION',
       'UNLAWFUL SALE - HANDGUN', 'OTHER WEAPONS VIOLATION',
       'MANUFACTURE / DELIVER - CRACK', 'INVOLUNTARY SERVITUDE',
       'MANUFACTURE / DELIVER - CANNABIS 10 GRAMS OR LESS',
       'AGGRAVATED PROTECTED EMPLOYEE - HANDGUN', 'IMPERSONATION',
       'THEFT / RECOVERY - TRUCK, BUS, MOBILE HOME',
       'POSSESS - HEROIN (TAN / BROWN TAR)',
       'UNLAWFUL VISITATION INTERFERENCE', 'FORFEIT PROPERTY',
       'ALTER / FORGE PRESCRIPTION', 'SOLICIT OFF PUBLIC WAY',
       'POSSESS FIREARM / AMMUNITION - NO FOID CARD',
       'THEFT BY LESSEE, NON-MOTOR VEHICLE', 'DELIVERY CONTAINER THEFT',
       'ATTEMPT AGGRAVATED - OTHER', 'ARSON THREAT',
       'GUN OFFENDER - DUTY TO REPORT CHANGE OF INFORMATION',
       'TAMPER WITH MOTOR VEHICLE', 'UNLAWFUL POSSESSION - OTHER FIREARM',
       'MANUFACTURE / DELIVER - METHAMPHETAMINE', 'TO AIRPORT',
       'PEEPING TOM', 'ARMED WHILE UNDER THE INFLUENCE',
       'ATTEMPT ARMED - OTHER FIREARM',
       'TIRE DEFLATION DEVICE DEPLOYMENT', 'PAROLE VIOLATION',
       'UNLAWFUL USE / SALE OF AIR RIFLE',
       'POSSESSION OF PORNOGRAPHIC PRINT',
       'VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE',
       'BOARD PLANE WITH WEAPON', 'POSSESS - AMPHETAMINES',
       'CRIMINAL DRUG CONSPIRACY',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE NO VIN',
       'SEX OFFENDER - PROHIBITED ZONE', 'ATTEMPT CRIMINAL SEXUAL ABUSE',
       'SEXUAL RELATIONS IN FAMILY', 'INSURANCE FRAUD',
       'INSTITUTIONAL VANDALISM',
       'MANUFACTURE / DELIVER - HEROIN (TAN / BROWN TAR)',
       'ATTEMPT - TRUCK, BUS, MOTOR HOME',
       'HAZARDOUS MATERIALS VIOLATION', 'ATTEMPT AGGRAVATED - HANDGUN',
       'ABUSE / NEGLECT - CARE FACILITY', 'MOB ACTION', 'OBSCENITY',
       'MANUFACTURE / DELIVER - COCAINE', 'RECKLESS HOMICIDE',
       'COMMERCIAL SEX ACTS', 'FORCIBLE DETENTION',
       'MANUFACTURE / DELIVER - BARBITURATES',
       'MANUFACTURE / DELIVER - SYNTHETIC DRUGS', 'EAVESDROPPING',
       'ATTEMPT - CYCLE, SCOOTER, BIKE NO VIN',
       'OTHER ARSON / EXPLOSIVE INCIDENT', 'PUBLIC DEMONSTRATION',
       'INTERFERENCE JUDICIAL PROCESS', 'ILLEGAL POSSESSION BY MINOR',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER FIREARM',
       'VIOLENT OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'MANUFACTURE / DELIVER - AMPHETAMINES',
       'VIOLENT OFFENDER - ANNUAL REGISTRATION',
       'OTHER PROSTITUTION OFFENSE',
       'ATTEMPT AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'MANUFACTURE / DELIVER - HALLUCINOGEN', 'BRIBERY',
       'INTOXICATING COMPOUNDS', 'VIOLATION OF SMOKING BAN',
       'SALE / DELIVER - DRUG PARAPHERNALIA',
       'CONCEALED CARRY LICENSE REVOCATION', 'FORNICATION',
       'LICENSED PREMISE', 'AGGRAVATED POLICE OFFICER - OTHER FIREARM',
       'FALSE FIRE ALARM', 'POSSESSION - EXPLOSIVE / INCENDIARY DEVICE',
       'FROM COIN-OPERATED MACHINE OR DEVICE',
       'AGGRAVATED OF AN UNBORN CHILD', 'ARSONIST - ANNUAL REGISTRATION',
       'ATTEMPT AGGRAVATED CRIMINAL SEXUAL ABUSE',
       'INTERFERE WITH EMERGENCY EQUIPMENT', 'POSSESS - LOOK-ALIKE DRUGS',
       'HARBOR RUNAWAY',
       'CONTRIBUTE TO THE CRIMINAL DELINQUENCY OF CHILD',
       'MANUFACTURE / DELIVER - SYNTHETIC MARIJUANA',
       'INTIMIDATION OF LAW ENFORCEMENT OFFICIAL',
       'DELIVER CANNABIS TO PERSON UNDER 18',
       'INDECENT SOLICITATION OF AN ADULT', 'MANUFACTURE / DELIVER - PCP',
       'CANNABIS PLANT', 'CRIMINAL TRANSMISSION OF HIV',
       'UNLAWFUL SALE - DELIVERY OF FIREARM AT SCHOOL',
       'ATTEMPT POSSESSION NARCOTICS', 'POSS: CRACK',
       'ILLEGAL CONSUMPTION BY MINOR', 'STRONGARM - NO WEAPON',
       'ATTEMPT AGGRAVATED - OTHER DANGEROUS WEAPON',
       'FALSE/STOLEN/ALTERED TRP', 'BY EXPLOSIVE',
       'FAILURE TO MAINTAIN RECORDS - CONTROLLED SUBSTANCES',
       'ATTEMPT POSSESSION CANNABIS', 'POSSESSION - SYNTHETIC MARIJUANA',
       'POSS: CANNABIS 30GMS OR LESS', 'ADULTRY', 'OFFICIAL MISCONDUCT',
       'ATTEMPT AGGRAVATED - OTHER FIREARM', 'BIGAMY',
       'MANUFACTURE / DELIVER - LOOK-ALIKE DRUG',
       'AGGRAVATED DOMESTIC BATTERY - OTHER FIREARM',
       'INVOLUNTARY MANSLAUGHTER',
       'DEFACE IDENTIFICATION MARKS OF FIREARM', 'ARMED: HANDGUN',
       'POSS: HEROIN(WHITE)', 'ATTEMPT: STRONGARM-NO WEAPON',
       'ATTEMPT: ARMED-HANDGUN', 'AGGRAVATED:KNIFE/CUTTING INSTR',
       'AGGRAVATED: HANDGUN', 'AGGRAVATED: OTHER FIREARM',
       'AGG: FINANCIAL ID THEFT', 'AGGRAVATED: OTHER DANG WEAPON',
       'POSS: SYNTHETIC DRUGS', 'POSS: COCAINE', 'AGGRAVATED: OTHER',
       'FINANCIAL ID THEFT:$300 &UNDER', 'CHILD ABDUCTION/STRANGER',
       'MANU/DELIVER:CRACK', 'POSS: HEROIN(BRN/TAN)',
       'AGG PO HANDS NO/MIN INJURY', 'FINANCIAL ID THEFT: OVER $300',
       'ATTEMPT: AGGRAVATED', 'SOLICIT FOR BUSINESS',
       'ALTER/FORGE PRESCRIPTION', 'MANU/DELIVER: HEROIN (WHITE)',
       'POSS: HALLUCINOGENS', 'ARMED:KNIFE/CUTTING INSTRUMENT',
       'CALL OPERATION', 'THEFT OF LABOR/SERVICES', 'ATT: AUTOMOBILE',
       'SOLICIT NARCOTICS ON PUBLICWAY', 'UNLAWFUL POSS OF HANDGUN',
       'MANU/DEL:CANNABIS 10GM OR LESS', 'UNLAWFUL USE OTHER DANG WEAPON',
       'AGG CRIMINAL SEXUAL ABUSE', 'THEFT BY LESSEE,NON-VEH',
       'MANU/DEL:CANNABIS OVER 10 GMS',
       'AGG: HANDS/FIST/FEET NO/MINOR INJURY',
       'SEX OFFENDER: FAIL REG NEW ADD', 'UNLAWFUL POSS AMMUNITION',
       'SEX OFFENDER: FAIL TO REGISTER', 'THEFT OF LOST/MISLAID PROP',
       'UNLAWFUL INTERFERE/VISITATION', 'POSS: CANNABIS MORE THAN 30GMS',
       'THEFT/RECOVERY: AUTOMOBILE', 'CRIM SEX ABUSE BY FAM MEMBER',
       'THEFT BY LESSEE,MOTOR VEH', 'TO STATE SUP PROP',
       'ARMED: OTHER DANGEROUS WEAPON', 'SELL/GIVE/DEL LIQUOR TO MINOR',
       'SALE/DEL HYPODERMIC NEEDLE', 'AGGRAVATED: KNIFE/CUT INSTR',
       'AGG RITUAL MUT:KNIFE/CUTTING I', 'AGG PRO.EMP:KNIFE/CUTTING INST',
       'ATT: TRUCK, BUS, MOTOR HOME', 'ATTEMPT: ARMED-KNIFE/CUT INSTR',
       'ENDANGERING LIFE/HEALTH CHILD', 'CYCLE, SCOOTER, BIKE W-VIN',
       'STOLEN PROP: BUY/RECEIVE/POS.', 'MANU/DELIVER:PCP',
       'UNLAWFUL POSS OTHER FIREARM', 'THEFT/RECOVERY: TRUCK,BUS,MHOME',
       'POSS: PCP', 'ATTEMPT: ARMED-OTHER DANG WEAP',
       'GAME/AMUSEMENT DEVICE', 'ATTEMPT: ARMED-OTHER FIREARM',
       'MANU/DELIVER:LOOK-ALIKE DRUG', 'UNLAWFUL USE HANDGUN',
       'POS: HYPODERMIC NEEDLE', 'SEX ASSLT OF CHILD BY FAM MBR',
       'AGG PRO.EMP: HANDGUN', 'UNLAWFUL USE/SALE AIR RIFLE',
       'FINAN EXPLOIT-ELDERLY/DISABLED', 'UNLAWFUL USE OTHER FIREARM',
       'ATTEMPT AGG: KNIFE/CUT INSTR', 'PRO EMP HANDS NO/MIN INJURY',
       'AGG SEX ASSLT OF CHILD FAM MBR',
       'CONTRIBUTE DELINQUENCY OF A CHILD', 'AGGRAVATED PO: HANDGUN',
       'ARMED: OTHER FIREARM', 'RESIST/OBSTRUCT/DISARM OFFICER',
       'UNLAWFUL USE OF RECORDED SOUND', 'ATTEMPT AGG: OTHER DANG WEAPON',
       'UNLAWFUL SALE HANDGUN', 'INDECENT SOLICITATION/CHILD',
       'AGGRAVATED PO: KNIFE/CUT INSTR', 'MANU/DELIVER:COCAINE',
       'ATT AGG CRIMINAL SEXUAL ABUSE', 'AGG RITUAL MUT:OTH DANG WEAPON',
       'PATRONIZING A PROSTITUTE', 'WIREROOM/SPORTS',
       'POSS FIREARM/AMMO:NO FOID CARD', 'GAME/CARDS',
       'AGGRAVATED PO: OTHER DANG WEAP', 'MANU/DELIVER:HEROIN(BLACK TAR)',
       'POSS: AMPHETAMINES', 'CAB OPERATION',
       'VIO BAIL BOND: DOM VIOLENCE', 'ATT CRIM SEXUAL ABUSE',
       'MANU/DELIVER: HALLUCINOGEN', 'POSS: BARBITUATES',
       'AGG CRIM SEX ABUSE FAM MEMBER', 'POSS: HEROIN(BLACK TAR)',
       'TO FIRE FIGHT.APP.EQUIP', 'POSS: LOOK-ALIKE DRUGS',
       'MANU/DELIVER: HEROIN(BRN/TAN)', 'VIOL CHARITABLE GAME ACT',
       'AGGRAVATED PO: OTHER FIREARM', 'DELIVER CANNABIS TO PERSON <18',
       'PAY TV SERVICE OFFENSES', 'MANU/DELIVER:AMPHETAMINES',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE W-VIN',
       'MANU/DELIVER:BARBITUATES', 'INDECENT SOLICITATION/ADULT',
       'AGGRAVATED PO:KNIFE/CUT INSTR', 'BOOKMAKING/SPORTS',
       'UNLAWFUL SALE OTHER FIREARM', 'DOMESTIC VIOLENCE',
       'REGISTER OF SALES BY DEALER', 'AGG PRO.EMP: OTHER DANG WEAPON',
       'ILLEGAL ILL LOTTERY', 'ATTEMPT AGG: HANDGUN',
       'SOLICIT FOR PROSTITUTE', 'MANU/DELIVER:SYNTHETIC DRUGS',
       'ATTEMPT AGG: OTHER', 'PIMPING', 'MINOR MISREPRESENT AGE',
       'IN TAVERN', 'PANDERING', 'POS: EXPLOSIVE/INCENDIARY DEV',
       'LOTTERY/OTHER', 'OTHER ARSON/EXPLOSIVE INCIDENT',
       'ATTEMPT: CYCLE, SCOOTER, BIKE W-VIN', 'BOOKMAKING/HORSES',
       'OVER $300', 'KEEP PLACE OF PROSTITUTION',
       'SALE/DIST OBSCENE MAT TO MINOR', 'LOOTING',
       'FINANCIAL IDENTITY THEFT: OVER $300',
       'POSS. KEYS OR DEV.TO COIN MACH', 'WIREROOM/HORSES',
       'ATT AGG CRIM SEXUAL ABUSE', '$300 AND UNDER',
       'DEFACE IDENT MARKS OF FIREARM', 'POLICY/OTHER',
       'REFUSING TO AID AN OFFICER', 'DEL CONT SUBS TO PERSON <18',
       'CONCEALING/AIDING A FUGITIVE', 'AGGRAVATED DOMESTIC BATTERY',
       'AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST',
       'SEX RELATION IN FAMILY', 'AGG RITUAL MUT:HANDGUN',
       'SEX OFFENDER: PROHIBITED ZONE', 'BOLITA OR BOLI PUL/WRITER',
       'BOLITA OR BOLI PUL/RUNNER', 'INTERFERE W/ HIGHER EDUCATION',
       'AGG PRO.EMP: OTHER FIREARM', 'LOTTERY/PARLAY CARDS',
       'ATTEMPT AGG: OTHER FIREARM', 'ANIMAL FIGHTING',
       'ANIMAL ABUSE/NEGLECT',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON',
       'CONTRIBUTE CRIM DELINQUENCY JUVENILE',
       'FROM COIN-OP MACHINE/DEVICE', 'VEHICLE TITLE/REG OFFENSE',
       'SELL/ADVERTISE FIREWORKS', 'POS: CHEMICAL/DRY-ICE DEVICE',
       'ALTER COINS', 'BOLITA OR BOLI PUL/OFFICE',
       'COMPELLING ORG MEMBERSHIP', 'UNIDENTIFIABLE RECORDING SOUND',
       'AGGRAVATED OF A UNBORN CHILD',
       'AGG RIT MUT: HANDS/FIST/FEET NO/MINOR INJURY',
       'SALE/DEL DRUG PARAPHERNALIA', 'COMPOUNDING A CRIME',
       'ABUSE/NEGLECT: CARE FACILITY', 'PROBATION VIOLATION',
       'OF UNBORN CHILD', 'UNLAWFUL SALE/DELIVERY OF FIREARM AT SCHOOL',
       'FIREARM REGISTRATION VIOLATION', 'LIBRARY VANDALISM',
       'JUVENILE PIMPING', 'PATRONIZE JUVENILE PROSTITUTE',
       'EDUCATIONAL INTIMIDAITON', 'POS: PORNOGRAPHIC PRINT',
       'CONTRABAND IN PRISON', 'LIBRARY THEFT',
       'ATTEMPT FINANCIAL IDENTITY THEFT', 'AGG PO HANDS ETC SERIOUS INJ',
       'CONT SUBS:FAIL TO MAINT RECORD',
       'AGG: HANDS/FIST/FEET SERIOUS INJURY',
       'AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY',
       'SALE TOBACCO PRODUCTS TO MINOR', 'AGG PRO EMP HANDS SERIOUS INJ',
       'AGGRAVATED DOMESTIC BATTERY: OTHER FIREARM',
       'AGGRAVATED DOMESTIC BATTERY: HANDGUN', 'AIDING ARRESTEE ESCAPE',
       'CALCULATED CANNABIS CONSPIRACY', 'MONEY LAUNDERING',
       'FAIL REGISTER LIC:CONT SUBS',
       'AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY',
       'UNLAWFUL USE OF BODY ARMOR', 'SPORTS TAMPERING',
       'MARRYING A BIGAMIST', 'REGISTER FED GAMBLING STAMP',
       'USE OF METAL PIERCING BULLETS', 'NATIONAL LOTTERY',
       'POSS: METHAMPHETAMINES', 'FAILURE TO KEEP HYPO RECORDS',
       'MANU/DELIVER: METHAMPHETAMINES', 'INTERFERE W/ EMERGENCY EQUIP',
       'COMPELLING CONFESSION',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE NO VIN',
       'KEEP PLACE OF JUV PROSTITUTION',
       'ATTEMPT: CYCLE, SCOOTER, BIKE NO VIN',
       'GUN OFFENDER: DUTY TO REGISTER', 'DISCLOSE DV VICTIM LOCATION',
       'POSSESSION: SYNTHETIC MARIJUANA',
       'MANU/POSS. W/INTENT TO DELIVER: SYNTHETIC MARIJUANA',
       'LOST PASSPORT', 'NOTIFICATION OF CIVIL NO CONTACT ORDER',
       'GUN OFFENDER: ANNUAL REGISTRATION', 'FOUND PASSPORT',
       'FOID - REVOCATION', 'VIOLENT OFFENDER: ANNUAL REGISTRATION',
       'GUN OFFENDER: DUTY TO REPORT CHANGE OF INFORMATION',
       'VIOLENT OFFENDER: FAIL TO REGISTER NEW ADDRESS',
       'VIOLENT OFFENDER: DUTY TO REGISTER',
       'NOTIFICATION OF STALKING - NO CONTACT ORDER',
       'GUN OFFENDER NOTIFICATION-NO CONTACT',
       'ARSONIST: ANNUAL REGISTRATION', 'VIOLATION OF SUMMARY CLOSURE',
       'THEFT RETAIL', 'ARSONIST: FAIL TO REGISTER NEW ADDRESS',
       'ARSONIST: DUTY TO REGISTER',
       'NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IMAGES',
       'AGGRAVATED: KNIFE / CUTTING INSTRUMENT',
       'AGGRAVATED: HANDS / FIST / FEET NO / MINOR INJURY',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANGEROUS WEAPON',
       'ARSONIST - FAIL TO REGISTER NEW ADDRESS', 'STRONGARM: NO WEAPON',
       'UNLAWFUL SALE - OTHER FIREARM',
       'AGGRAVATED DOMESTIC BATTERY: KNIFE / CUTTING INSTSTRUMENT',
       'AGGRAVATED: OTHER DANGEROUS WEAPON',
       'ATTEMPT STRONG ARM: NO WEAPON', 'ATTEMPT ARMED: HANDGUN',
       'SALE OF TOBACCO PRODUCTS TO MINOR', 'GAME / AMUSEMENT DEVICE',
       'SOLICITING FOR A PROSTITUTE',
       'AGGRAVATED PO: OTHER DANGEROUS WEAPON',
       'AGGRAVATED: HANDS / FIST / FEET SERIOUS INJURY',
       'PROTECTED EMPLOYEE: HANDS NO / MIN INJURY',
       'MANUFACTURE / DELIVER - HEROIN (BLACK TAR)',
       'AGG. RITUAL MUTILATION - HANDS, FISTS, FEET, SERIOUS INJURY',
       'SELL / ADVERTISE FIREWORKS',
       'DISCLOSE DOMESTIC VIOLENCE VICTIM LOCATION',
       'SECOND DEGREE MURDER', 'POSSESS - HYPODERMIC NEEDLE',
       'DELIVER CONTROLLED SUBSTANCES TO PERSON UNDER 18',
       'POSSESS KEYS OR DEVICE TO COIN MACHINE'], dtype=object)

In [ ]:
df['Description'].nunique()

549

In [ ]:
# Primary type column grouping the similar ones.

mapping={'MOTOR VEHICLE THEFT':'THEFT', 'SEX OFFENSE':'CRIMINAL SEXUAL ASSAULT',  'CRIM SEXUAL ASSAULT':'CRIMINAL SEXUAL ASSAULT', 'NON-CRIMINAL (SUBJECT SPECIFIED)':'NON-CRIMINAL','NON - CRIMINAL':'NON-CRIMINAL'}

In [ ]:

df['Primary Type']=df['Primary Type'].replace(mapping)

In [ ]:
# df.to_csv('crime_data1.csv',index=False)

In [2]:
import pandas as pd
data=pd.read_csv(r'C:\Users\Good Day\Desktop\projects\crime_data1.csv')

In [15]:
print('hi')

hi

In [ ]:
import mysql.connector

: